# Generated by Django 5.2.1 on 2025-05-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'due_date']},
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('STUDY', 'Study'), ('WORK', 'Work'), ('PERSONAL', 'Personal'), ('OTHER', 'Other')], default='STUDY', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes'),
        ),
    ]
